language: node_js
cache:
  directories:
  - "~!@/.npm"
node_js:
- '9'
git:
  depth: 3
script:
- yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: "$GITHUB_TOKEN"
  local-dir: build/
  target-branch: master
  commit_message: Deploy release ${TRAVIS_TAG}
  on:
    branch: develop
env:
  global:
  - secure: "GyFWXjDMaeQ/SNGvuqU9tgNbpIoLEM9p9gJGZnXcxXCpmIXcny9PJFb6nF4r+TUQ3pMi1e5EWpDIIFW9Kl+OjhGlK6hPk2roamCt7ugZhbyDe6z8G3Im83PvatZ0bcGvpm+SJSc13uIvkGLsXL6KJBuGbAzA7Zy/kWDltVinSQAqboYuFuW/uuWNBOPM5gHrwjO/nliaXSyZs1xQhxtidmmhvLAOFQw0i7Y684dyuvyM6WCN41q7XhAh4sxHV5cdCDFeA8pO02TOctk2PjDZF8pJ24dS4EzxiBO//k3W/0CAQ3d7NrD93ZJN6SEtcGI2+jSE5c1vKziNpkxD8Y//HLvDpR97eS3VBiNJw+6HRD+JUnat4A2uQAYi7PKD8Dul6UQmoOEVzZezpbfpmPhIIlxBMv8FhHh5EVvDGNp87xFg9EPPOqTRH/9yW99US7R2jSsjyqxbpMsdIMS9PCMLS/EtJ2j+aD8ANT1pOAXfGvMix7WSD4Cy2XiCH7eJ+G1HA2YV1z9lE9tXTbH9cUNJxvACT8Pfyl+4+UvAVi61Zl/M5tzIZGldM323KCeERWVS4YNPLaXC258hHdkYeRcEV4xnDd743JjDMzSdOSSfClay0KAV5nnzuGpIAu7XZNI0366pKEYVALAhKxVs/s0m12mzqbixPp767y+kuMdoIIY="
